In [1]:
import numpy as np

In [2]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [4]:
b = a.reshape(2, 4, 3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [9]:
x = np.zeros(5, dtype=np.int_)
print(x)

[0 0 0 0 0]


In [11]:
x = np.linspace(10, 20, 5, endpoint=False)
print(x)

[10. 12. 14. 16. 18.]


In [13]:
a = np.logspace(1.0, 2.0, num=10, base=2)
print(a)

[2.         2.16011948 2.33305808 2.5198421  2.72158    2.93946898
 3.1748021  3.42897593 3.70349885 4.        ]
