In [1]:
import numpy as np

In [2]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
s = slice(2, 7, 2)
print(a[s])

[2 4 6]


In [8]:
b = a[2:7:2]
print(b)

[2 4 6]


In [10]:
print(a[4:])

[4 5 6 7 8 9]


In [11]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(a[1:])

[[4 5 6]
 [7 8 9]]


In [13]:
b = a[[0,1,2], [0,1,0]]
print(b)

[1 5 7]


In [15]:
c = a[[0], [1]]
print(c)

[2]


In [16]:
x = np.array([[0,1,2], [3,4,5], [6,7,8], [9, 10, 11]])
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [17]:
row = np.array([[0,0], [3,3]])
cols = np.array([[0,2], [0,2]])
y = x[row, cols]
print(y)

[[ 0  2]
 [ 9 11]]


In [18]:
print(x[x>5])

[ 6  7  8  9 10 11]
