In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3,4])
b = np.array([10, 20, 30, 40])
c = a * b
print(c)

[ 10  40  90 160]


In [3]:
a  = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([1,2,3])
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


In [4]:
print(a+b)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
